### PR TITLE
Areal chapters

### PR DESCRIPTION
**Pull request by rsbivand**
Areal chapters adapted

### CODE REVIEW

**Comment by rsbivand** [comment]
I cannot build the HTML locally, multiple blocks fail.

**Comment by edzer** [comment]
For checking particular chapters, I uncomment (with #) all other chapters in `_quarto.yml`.

**Comment by rsbivand** [comment]
No such file in this repo, I just want to build `answers.html`.

**Comment by edzer** [comment]
Yes, I see there's an error, seems sth in `extractextractr` changed...

**Comment by edzer** [comment]
Shoud work again, with stars (quick fix) from github.

**Comment by rsbivand** [comment]
How to generate vst.RData, new_ts.RData, new_int.RData needed to recreate ch13.RData needed to build `answers.html`? OK, work around the block markup ... for each missing file, and:
```
Warning in supportsMulticoreAndRStudio(...) :
  [ONE-TIME WARNING] Forked processing ('multicore') is not supported when running R from RStudio because it is considered unstable. For more details, how to control forked processing or not, and how to silence this warning in future R sessions, see ?parallelly::supportsMulticore
```
which is an excellent reason to drop rstudio, if they can't do it right.

**Comment by edzer** [comment]
Is it OK if I rearrange this repo as a quarto book, so we have chapter and can outcomment them in the _quarto.yml?

**Comment by rsbivand** [comment]
Yes, that is sensible.

**Comment by rsbivand** [comment]
Built `answers.html` now.

**Comment by edzer** [comment]
OK hang on - quarto migration underway.

**Comment by edzer** [comment]
done.

**Comment by rsbivand** [comment]
Picked up, but:
```
$ make all
quarto render
make: quarto: No such file or directory
make: *** [makefile:2: all] Error 127
```
What is quarto? No Fedora 36 quarto available. They only make in-house binaries, no open source, sorry, no use to me. I have to try to render each chapter separately? In Rstudio?

**Comment by edzer** [comment]
```
R -e 'knitr::knit2html("07.qmd")'
```

**Pull request merged**
